# Generated by Django 3.1.6 on 2021-02-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_color_productlang_size_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_ar',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
