# Generated by Django 3.1.6 on 2021-02-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210216_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug_ar',
            field=models.SlugField(allow_unicode=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, null=True),
        ),
    ]
