# Generated by Django 3.1.6 on 2021-02-21 19:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210221_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
